// Code generated by protoc-gen-go. DO NOT EDIT.
// source: graphql/options.proto

package graphql // import "github.com/martinxsliu/protoc-gen-graphql/protobuf/graphql"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceOptions struct {
	// A variable-like name to reference the service with, in lieu of the
	// name generated from the service's package and service name. The name
	// should be short, snake cased, and unique across all services.
	ReferenceName        string   `protobuf:"bytes,1,opt,name=reference_name,json=referenceName,proto3" json:"reference_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceOptions) Reset()         { *m = ServiceOptions{} }
func (m *ServiceOptions) String() string { return proto.CompactTextString(m) }
func (*ServiceOptions) ProtoMessage()    {}
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_271333f07818dee0, []int{0}
}
func (m *ServiceOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceOptions.Unmarshal(m, b)
}
func (m *ServiceOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceOptions.Marshal(b, m, deterministic)
}
func (m *ServiceOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceOptions.Merge(m, src)
}
func (m *ServiceOptions) XXX_Size() int {
	return xxx_messageInfo_ServiceOptions.Size(m)
}
func (m *ServiceOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceOptions proto.InternalMessageInfo

func (m *ServiceOptions) GetReferenceName() string {
	if m != nil {
		return m.ReferenceName
	}
	return ""
}

type MethodOptions struct {
	// Type of GraphQL operation. Valid values are: "query", "mutation",
	// or "subscription". Defaults to "query".
	Operation            string   `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodOptions) Reset()         { *m = MethodOptions{} }
func (m *MethodOptions) String() string { return proto.CompactTextString(m) }
func (*MethodOptions) ProtoMessage()    {}
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_271333f07818dee0, []int{1}
}
func (m *MethodOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodOptions.Unmarshal(m, b)
}
func (m *MethodOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodOptions.Marshal(b, m, deterministic)
}
func (m *MethodOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodOptions.Merge(m, src)
}
func (m *MethodOptions) XXX_Size() int {
	return xxx_messageInfo_MethodOptions.Size(m)
}
func (m *MethodOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MethodOptions proto.InternalMessageInfo

func (m *MethodOptions) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

var E_ServiceOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*ServiceOptions)(nil),
	Field:         82731,
	Name:          "graphql.service_options",
	Tag:           "bytes,82731,opt,name=service_options,json=serviceOptions",
	Filename:      "graphql/options.proto",
}

var E_MethodOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*MethodOptions)(nil),
	Field:         82731,
	Name:          "graphql.method_options",
	Tag:           "bytes,82731,opt,name=method_options,json=methodOptions",
	Filename:      "graphql/options.proto",
}

func init() {
	proto.RegisterType((*ServiceOptions)(nil), "graphql.ServiceOptions")
	proto.RegisterType((*MethodOptions)(nil), "graphql.MethodOptions")
	proto.RegisterExtension(E_ServiceOptions)
	proto.RegisterExtension(E_MethodOptions)
}

func init() { proto.RegisterFile("graphql/options.proto", fileDescriptor_271333f07818dee0) }

var fileDescriptor_271333f07818dee0 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xd9, 0x83, 0xca, 0x46, 0x5a, 0xa1, 0xa0, 0x2e, 0x22, 0x5a, 0x16, 0x84, 0xbd, 0x34,
	0x05, 0x3d, 0x08, 0xc5, 0x93, 0x77, 0x15, 0xea, 0xcd, 0x4b, 0x69, 0xb3, 0xb3, 0x6d, 0xa0, 0xc9,
	0xc4, 0x24, 0x15, 0x9f, 0xc0, 0x97, 0xf1, 0x25, 0xc5, 0x26, 0x8d, 0x56, 0x8f, 0xf3, 0x65, 0x26,
	0xff, 0x97, 0x09, 0x39, 0x6e, 0x75, 0xad, 0xba, 0xd7, 0x3e, 0x47, 0x65, 0x39, 0x4a, 0x43, 0x95,
	0x46, 0x8b, 0xc9, 0x81, 0xc7, 0x67, 0x69, 0x8b, 0xd8, 0xf6, 0x90, 0x8f, 0xb8, 0x19, 0x76, 0xf9,
	0x16, 0x0c, 0xd3, 0x5c, 0x59, 0xd4, 0xae, 0x75, 0x7d, 0x4b, 0xe2, 0x67, 0xd0, 0x6f, 0x9c, 0xc1,
	0x93, 0xbb, 0x22, 0xb9, 0x22, 0xb1, 0x86, 0x1d, 0x68, 0x90, 0x0c, 0x2a, 0x59, 0x0b, 0x58, 0x2d,
	0xd2, 0xc5, 0x66, 0x59, 0x46, 0x81, 0x3e, 0xd6, 0x02, 0xd6, 0x19, 0x89, 0x1e, 0xc0, 0x76, 0xb8,
	0x9d, 0xe6, 0xce, 0xc9, 0x12, 0x15, 0xe8, 0xfa, 0xbb, 0xf2, 0x23, 0x3f, 0xa0, 0x60, 0xe4, 0xc8,
	0xb8, 0x9c, 0xca, 0xbb, 0x26, 0x97, 0xd4, 0xd9, 0xd1, 0xc9, 0x8e, 0xce, 0x4d, 0x56, 0x9f, 0x1f,
	0x7b, 0xe9, 0x62, 0x73, 0x78, 0x7d, 0x4a, 0xfd, 0x7b, 0xfe, 0x34, 0x94, 0xb1, 0x99, 0xd5, 0x45,
	0x45, 0x62, 0x31, 0x3a, 0x85, 0x8c, 0x8b, 0x7f, 0x19, 0x33, 0xe9, 0x10, 0x71, 0x12, 0x22, 0x66,
	0xe7, 0x65, 0x24, 0x7e, 0x97, 0xf7, 0x77, 0x2f, 0x45, 0xcb, 0x6d, 0x37, 0x34, 0x94, 0xa1, 0xc8,
	0x45, 0xad, 0x2d, 0x97, 0xef, 0xa6, 0xe7, 0x83, 0xdb, 0x30, 0xcb, 0x5a, 0x90, 0xd9, 0xf4, 0x27,
	0x61, 0xe9, 0x1e, 0x34, 0xfb, 0x23, 0xb9, 0xf9, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x8a, 0x7b,
	0x33, 0xb6, 0x01, 0x00, 0x00,
}
