// Code generated by protoc-gen-go. DO NOT EDIT.
// source: graphql/options.proto

package graphql

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileOptions struct {
	// Name used to prefix all types with. If unset, the default behaviour is
	// to use the upper camel case of the Protobuf package name.
	Namespace            *string  `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileOptions) Reset()         { *m = FileOptions{} }
func (m *FileOptions) String() string { return proto.CompactTextString(m) }
func (*FileOptions) ProtoMessage()    {}
func (*FileOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_271333f07818dee0, []int{0}
}

func (m *FileOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileOptions.Unmarshal(m, b)
}
func (m *FileOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileOptions.Marshal(b, m, deterministic)
}
func (m *FileOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileOptions.Merge(m, src)
}
func (m *FileOptions) XXX_Size() int {
	return xxx_messageInfo_FileOptions.Size(m)
}
func (m *FileOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_FileOptions.DiscardUnknown(m)
}

var xxx_messageInfo_FileOptions proto.InternalMessageInfo

func (m *FileOptions) GetNamespace() string {
	if m != nil && m.Namespace != nil {
		return *m.Namespace
	}
	return ""
}

type MessageOptions struct {
	// Name of the generated GraphQL type.
	Type                 *string  `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageOptions) Reset()         { *m = MessageOptions{} }
func (m *MessageOptions) String() string { return proto.CompactTextString(m) }
func (*MessageOptions) ProtoMessage()    {}
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_271333f07818dee0, []int{1}
}

func (m *MessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageOptions.Unmarshal(m, b)
}
func (m *MessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageOptions.Marshal(b, m, deterministic)
}
func (m *MessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageOptions.Merge(m, src)
}
func (m *MessageOptions) XXX_Size() int {
	return xxx_messageInfo_MessageOptions.Size(m)
}
func (m *MessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MessageOptions proto.InternalMessageInfo

func (m *MessageOptions) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

type FieldOptions struct {
	// Name of the field in the generated GraphQL object and input types.
	Field *string `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	// Name of GraphQL type to use for this field, including modifiers.
	Type *string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	// Skip this field from being generated.
	Skip *bool `protobuf:"varint,3,opt,name=skip" json:"skip,omitempty"`
	// GraphQL directive to generate for the field. Do not include the @ sign,
	// do include any arguments within parentheses.
	Directive []string `protobuf:"bytes,4,rep,name=directive" json:"directive,omitempty"`
	// Mark the field as a foreign key to another Protobuf message, and include
	// the referenced message as a field of the generated GraphQL type.
	//
	// The value is expected to have the form:
	//
	//   "<protobuf_type>:<field_name>",
	//
	// * 'protobuf_type' is the fully qualified name of the Protobuf type.
	// * 'field_name' is the name of the field in the generated GraphQL type.
	//
	// For example:
	//
	// message User {
	//   string address_id = 1 [(graphql.field).foreign_key = "my.package.Address:address"];
	// }
	//
	// will generate the GraphQL type:
	//
	// type MyPackage_User {
	//   addressId: String!
	//   address: MyPackage_Address
	// }
	ForeignKey           *string  `protobuf:"bytes,5,opt,name=foreign_key,json=foreignKey" json:"foreign_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldOptions) Reset()         { *m = FieldOptions{} }
func (m *FieldOptions) String() string { return proto.CompactTextString(m) }
func (*FieldOptions) ProtoMessage()    {}
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_271333f07818dee0, []int{2}
}

func (m *FieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldOptions.Unmarshal(m, b)
}
func (m *FieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldOptions.Marshal(b, m, deterministic)
}
func (m *FieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldOptions.Merge(m, src)
}
func (m *FieldOptions) XXX_Size() int {
	return xxx_messageInfo_FieldOptions.Size(m)
}
func (m *FieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_FieldOptions proto.InternalMessageInfo

func (m *FieldOptions) GetField() string {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return ""
}

func (m *FieldOptions) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *FieldOptions) GetSkip() bool {
	if m != nil && m.Skip != nil {
		return *m.Skip
	}
	return false
}

func (m *FieldOptions) GetDirective() []string {
	if m != nil {
		return m.Directive
	}
	return nil
}

func (m *FieldOptions) GetForeignKey() string {
	if m != nil && m.ForeignKey != nil {
		return *m.ForeignKey
	}
	return ""
}

type EnumOptions struct {
	// Name of the generated GraphQL type.
	Type                 *string  `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnumOptions) Reset()         { *m = EnumOptions{} }
func (m *EnumOptions) String() string { return proto.CompactTextString(m) }
func (*EnumOptions) ProtoMessage()    {}
func (*EnumOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_271333f07818dee0, []int{3}
}

func (m *EnumOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumOptions.Unmarshal(m, b)
}
func (m *EnumOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumOptions.Marshal(b, m, deterministic)
}
func (m *EnumOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumOptions.Merge(m, src)
}
func (m *EnumOptions) XXX_Size() int {
	return xxx_messageInfo_EnumOptions.Size(m)
}
func (m *EnumOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumOptions.DiscardUnknown(m)
}

var xxx_messageInfo_EnumOptions proto.InternalMessageInfo

func (m *EnumOptions) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

type EnumValueOptions struct {
	// Name of the enum value in the generated GraphQL enum type.
	Value                *string  `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnumValueOptions) Reset()         { *m = EnumValueOptions{} }
func (m *EnumValueOptions) String() string { return proto.CompactTextString(m) }
func (*EnumValueOptions) ProtoMessage()    {}
func (*EnumValueOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_271333f07818dee0, []int{4}
}

func (m *EnumValueOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumValueOptions.Unmarshal(m, b)
}
func (m *EnumValueOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumValueOptions.Marshal(b, m, deterministic)
}
func (m *EnumValueOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumValueOptions.Merge(m, src)
}
func (m *EnumValueOptions) XXX_Size() int {
	return xxx_messageInfo_EnumValueOptions.Size(m)
}
func (m *EnumValueOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumValueOptions.DiscardUnknown(m)
}

var xxx_messageInfo_EnumValueOptions proto.InternalMessageInfo

func (m *EnumValueOptions) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type ServiceOptions struct {
	// A variable-like name to reference the service with, in lieu of the
	// name generated from the service's package and service name. The name
	// should be unique across all gRPC services.
	// Note: This will not be the name of the generated GraphQL type.
	ReferenceName *string `protobuf:"bytes,1,opt,name=reference_name,json=referenceName" json:"reference_name,omitempty"`
	// Skip this service from being generated.
	Skip                 *bool    `protobuf:"varint,2,opt,name=skip" json:"skip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceOptions) Reset()         { *m = ServiceOptions{} }
func (m *ServiceOptions) String() string { return proto.CompactTextString(m) }
func (*ServiceOptions) ProtoMessage()    {}
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_271333f07818dee0, []int{5}
}

func (m *ServiceOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceOptions.Unmarshal(m, b)
}
func (m *ServiceOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceOptions.Marshal(b, m, deterministic)
}
func (m *ServiceOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceOptions.Merge(m, src)
}
func (m *ServiceOptions) XXX_Size() int {
	return xxx_messageInfo_ServiceOptions.Size(m)
}
func (m *ServiceOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceOptions proto.InternalMessageInfo

func (m *ServiceOptions) GetReferenceName() string {
	if m != nil && m.ReferenceName != nil {
		return *m.ReferenceName
	}
	return ""
}

func (m *ServiceOptions) GetSkip() bool {
	if m != nil && m.Skip != nil {
		return *m.Skip
	}
	return false
}

type MethodOptions struct {
	// Name of the field in the GraphQL type generated for the service.
	Field *string `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	// Type of GraphQL operation. Valid values are: "query", "mutation",
	// or "subscription". Defaults to "query".
	Operation *string `protobuf:"bytes,2,opt,name=operation" json:"operation,omitempty"`
	// Mark the gRPC method as one that can load a single instance of a Protobuf
	// message from a key identifier.
	//
	// The value is expected to have the form:
	//
	//   "<protobuf_type>:<request_field_path>:<response_field_path>"
	//
	// * 'protobuf_type' is the fully qualified name of the Protobuf type.
	// * 'request_field_path' is the dot separated field path in the gRPC method's
	//   request message to the field representing the key. The key field must be
	//   a scalar field.
	// * 'response_field_path' is the dot separated field path in the gRPC
	//   method's response message to the field representing the loaded Protobuf
	//   message. The loaded message must have the same type as the type
	//   specified by 'protobuf_type'.
	// Field paths have the same semantics as the well known FieldMask type.
	//
	// For example:
	//
	// service Users {
	//   rpc GetUser(GetUserRequest) returns (GetUserResponse) {
	//     option (graphql.method) = { load_one = "my.package.User:identifier.value:user" };
	//   };
	// }
	//
	// message GetUserRequest {
	//   message Identifier {
	//     string value = 1;
	//   }
	//   message Email {
	//     string value = 1;
	//   }
	//
	//   oneof input {
	//     Identifier identifier = 1;
	//     Email email = 2;
	//   }
	// }
	//
	// message GetUserResponse {
	//   User user = 1;
	// }
	//
	LoadOne *string `protobuf:"bytes,3,opt,name=load_one,json=loadOne" json:"load_one,omitempty"`
	// Mark the gRPC method as one that can load multiple instances of a Protobuf
	// message from a set of key identifiers. The value is expected to have the
	// same form as the 'load_one' option, except that the key field specified
	// by the 'request_field_path' and the loaded field specified by the
	// 'response_field_path' must both be repeated fields.
	LoadMany *string `protobuf:"bytes,4,opt,name=load_many,json=loadMany" json:"load_many,omitempty"`
	// Skip this method from being generated.
	Skip                 *bool    `protobuf:"varint,5,opt,name=skip" json:"skip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodOptions) Reset()         { *m = MethodOptions{} }
func (m *MethodOptions) String() string { return proto.CompactTextString(m) }
func (*MethodOptions) ProtoMessage()    {}
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_271333f07818dee0, []int{6}
}

func (m *MethodOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodOptions.Unmarshal(m, b)
}
func (m *MethodOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodOptions.Marshal(b, m, deterministic)
}
func (m *MethodOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodOptions.Merge(m, src)
}
func (m *MethodOptions) XXX_Size() int {
	return xxx_messageInfo_MethodOptions.Size(m)
}
func (m *MethodOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MethodOptions proto.InternalMessageInfo

func (m *MethodOptions) GetField() string {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return ""
}

func (m *MethodOptions) GetOperation() string {
	if m != nil && m.Operation != nil {
		return *m.Operation
	}
	return ""
}

func (m *MethodOptions) GetLoadOne() string {
	if m != nil && m.LoadOne != nil {
		return *m.LoadOne
	}
	return ""
}

func (m *MethodOptions) GetLoadMany() string {
	if m != nil && m.LoadMany != nil {
		return *m.LoadMany
	}
	return ""
}

func (m *MethodOptions) GetSkip() bool {
	if m != nil && m.Skip != nil {
		return *m.Skip
	}
	return false
}

var E_File = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*FileOptions)(nil),
	Field:         82731,
	Name:          "graphql.file",
	Tag:           "bytes,82731,opt,name=file",
	Filename:      "graphql/options.proto",
}

var E_Message = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*MessageOptions)(nil),
	Field:         82731,
	Name:          "graphql.message",
	Tag:           "bytes,82731,opt,name=message",
	Filename:      "graphql/options.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldOptions)(nil),
	Field:         82731,
	Name:          "graphql.field",
	Tag:           "bytes,82731,opt,name=field",
	Filename:      "graphql/options.proto",
}

var E_Enum = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*EnumOptions)(nil),
	Field:         82731,
	Name:          "graphql.enum",
	Tag:           "bytes,82731,opt,name=enum",
	Filename:      "graphql/options.proto",
}

var E_EnumValue = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*EnumValueOptions)(nil),
	Field:         82731,
	Name:          "graphql.enum_value",
	Tag:           "bytes,82731,opt,name=enum_value",
	Filename:      "graphql/options.proto",
}

var E_Service = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*ServiceOptions)(nil),
	Field:         82731,
	Name:          "graphql.service",
	Tag:           "bytes,82731,opt,name=service",
	Filename:      "graphql/options.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*MethodOptions)(nil),
	Field:         82731,
	Name:          "graphql.method",
	Tag:           "bytes,82731,opt,name=method",
	Filename:      "graphql/options.proto",
}

func init() {
	proto.RegisterType((*FileOptions)(nil), "graphql.FileOptions")
	proto.RegisterType((*MessageOptions)(nil), "graphql.MessageOptions")
	proto.RegisterType((*FieldOptions)(nil), "graphql.FieldOptions")
	proto.RegisterType((*EnumOptions)(nil), "graphql.EnumOptions")
	proto.RegisterType((*EnumValueOptions)(nil), "graphql.EnumValueOptions")
	proto.RegisterType((*ServiceOptions)(nil), "graphql.ServiceOptions")
	proto.RegisterType((*MethodOptions)(nil), "graphql.MethodOptions")
	proto.RegisterExtension(E_File)
	proto.RegisterExtension(E_Message)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Enum)
	proto.RegisterExtension(E_EnumValue)
	proto.RegisterExtension(E_Service)
	proto.RegisterExtension(E_Method)
}

func init() { proto.RegisterFile("graphql/options.proto", fileDescriptor_271333f07818dee0) }

var fileDescriptor_271333f07818dee0 = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x51, 0x8b, 0xd3, 0x4c,
	0x14, 0xa5, 0xbb, 0xed, 0xd7, 0xcd, 0xed, 0xb7, 0x45, 0x86, 0x5d, 0xcd, 0x6a, 0x75, 0xbb, 0x41,
	0xa1, 0x20, 0x9b, 0x82, 0x8f, 0xc1, 0x27, 0xc1, 0x45, 0x58, 0xeb, 0x4a, 0x14, 0x1f, 0x04, 0x29,
	0xb3, 0xe9, 0x6d, 0x3a, 0x6c, 0x32, 0x13, 0x27, 0x49, 0xb1, 0x7f, 0xc0, 0x17, 0x1f, 0xfc, 0x21,
	0xfe, 0x49, 0x99, 0x49, 0x32, 0x99, 0x62, 0xd0, 0xa7, 0xf6, 0x9e, 0x7b, 0xee, 0xe1, 0xde, 0x93,
	0xc3, 0xc0, 0x69, 0x2c, 0x69, 0xb6, 0xf9, 0x9a, 0xcc, 0x45, 0x56, 0x30, 0xc1, 0x73, 0x3f, 0x93,
	0xa2, 0x10, 0x64, 0x58, 0xc3, 0x0f, 0xa7, 0xb1, 0x10, 0x71, 0x82, 0x73, 0x0d, 0xdf, 0x96, 0xeb,
	0xf9, 0x0a, 0xf3, 0x48, 0xb2, 0xac, 0x10, 0xb2, 0xa2, 0x7a, 0xcf, 0x61, 0x74, 0xc5, 0x12, 0xbc,
	0xa9, 0xe6, 0xc9, 0x04, 0x1c, 0x4e, 0x53, 0xcc, 0x33, 0x1a, 0xa1, 0xdb, 0x9b, 0xf6, 0x66, 0x4e,
	0xd8, 0x02, 0xde, 0x53, 0x18, 0x2f, 0x30, 0xcf, 0x69, 0x6c, 0xf8, 0x04, 0xfa, 0xc5, 0x2e, 0x6b,
	0xa8, 0xfa, 0xbf, 0xf7, 0xa3, 0x07, 0xff, 0x5f, 0x31, 0x4c, 0x56, 0x0d, 0xe9, 0x04, 0x06, 0x6b,
	0x55, 0xd7, 0xac, 0xaa, 0x30, 0xa3, 0x07, 0xed, 0xa8, 0xc2, 0xf2, 0x3b, 0x96, 0xb9, 0x87, 0xd3,
	0xde, 0xec, 0x28, 0xd4, 0xff, 0xd5, 0x4a, 0x2b, 0x26, 0x31, 0x2a, 0xd8, 0x16, 0xdd, 0xfe, 0xf4,
	0x50, 0xad, 0x64, 0x00, 0x72, 0x0e, 0xa3, 0xb5, 0x90, 0xc8, 0x62, 0xbe, 0xbc, 0xc3, 0x9d, 0x3b,
	0xd0, 0x62, 0x50, 0x43, 0xd7, 0xb8, 0xf3, 0x2e, 0x60, 0xf4, 0x9a, 0x97, 0xe9, 0xdf, 0x16, 0x9e,
	0xc1, 0x3d, 0x45, 0xf9, 0x44, 0x93, 0x12, 0xad, 0x9d, 0xb7, 0xaa, 0x6e, 0x76, 0xd6, 0x85, 0x77,
	0x0d, 0xe3, 0x0f, 0x28, 0xb7, 0x2c, 0x32, 0xbc, 0x67, 0x30, 0x96, 0xb8, 0x46, 0x89, 0x3c, 0xc2,
	0xa5, 0x72, 0xaa, 0x1e, 0x38, 0x36, 0xe8, 0x3b, 0x9a, 0xb6, 0x87, 0x1d, 0xb4, 0x87, 0x79, 0x3f,
	0x7b, 0x70, 0xbc, 0xc0, 0x62, 0x23, 0xfe, 0x61, 0xd4, 0x04, 0x1c, 0x91, 0xa1, 0xa4, 0x8a, 0x53,
	0xbb, 0xd5, 0x02, 0xe4, 0x0c, 0x8e, 0x12, 0x41, 0x57, 0x4b, 0xc1, 0x51, 0xdb, 0xe6, 0x84, 0x43,
	0x55, 0xdf, 0x70, 0x24, 0x8f, 0xc0, 0xd1, 0xad, 0x94, 0xf2, 0x9d, 0xdb, 0xd7, 0x3d, 0xcd, 0x5d,
	0x50, 0xbe, 0x33, 0x1b, 0x0d, 0xda, 0x8d, 0x82, 0x37, 0xd0, 0x5f, 0xb3, 0x04, 0xc9, 0xc4, 0xaf,
	0x72, 0xe3, 0x37, 0xb9, 0xf1, 0xad, 0x8c, 0xb8, 0xbf, 0xbe, 0xab, 0x99, 0xd1, 0x8b, 0x13, 0xbf,
	0x8e, 0x99, 0xdd, 0x0d, 0xb5, 0x42, 0xf0, 0x11, 0x86, 0x69, 0x95, 0x14, 0x72, 0xfe, 0x87, 0xd8,
	0x7e, 0x86, 0x8c, 0xde, 0x03, 0xa3, 0xb7, 0x4f, 0x08, 0x1b, 0xa9, 0xe0, 0x6d, 0xed, 0x0f, 0x79,
	0xdc, 0xb1, 0x60, 0x1b, 0x38, 0xa3, 0x78, 0x6a, 0x6d, 0xd8, 0xb6, 0x6b, 0x5f, 0xd5, 0xb5, 0xc8,
	0xcb, 0xb4, 0xe3, 0x5a, 0x2b, 0x30, 0x1d, 0xd7, 0x5a, 0xdd, 0x50, 0x2b, 0x04, 0x5f, 0x00, 0xd4,
	0xef, 0x52, 0x87, 0x84, 0x5c, 0x74, 0xea, 0xd9, 0xe9, 0x32, 0xa2, 0x67, 0x7b, 0xa2, 0x36, 0x25,
	0x74, 0xb0, 0x41, 0x94, 0x99, 0x79, 0x95, 0xba, 0x0e, 0x33, 0xf7, 0xf3, 0xd8, 0x61, 0xe6, 0x3e,
	0x21, 0x6c, 0xa4, 0x82, 0xf7, 0xf0, 0x5f, 0xaa, 0xd3, 0x47, 0x9e, 0x74, 0x7c, 0x21, 0x2b, 0x96,
	0x46, 0xf3, 0xbe, 0xf5, 0x81, 0xac, 0x7e, 0x58, 0xeb, 0xbc, 0x7a, 0xf9, 0x39, 0x88, 0x59, 0xb1,
	0x29, 0x6f, 0xfd, 0x48, 0xa4, 0xf3, 0x94, 0xca, 0x82, 0xf1, 0x6f, 0x79, 0xc2, 0xca, 0xea, 0xfd,
	0x89, 0x2e, 0x63, 0xe4, 0x97, 0xcd, 0x8b, 0x65, 0x9e, 0xa4, 0x1a, 0xf8, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0xd8, 0xbc, 0x1e, 0x4a, 0xcc, 0x04, 0x00, 0x00,
}
